### ISSUE TITLE
TimePrinter (task 3)

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#1]
[TimePrinter](https://github.com/javamasterpeople/javacorestart/blob/master/src/TimePrinter.java) 

Задача решена верно.

**Рекомендации по улучшению** - разбить код на методы для каждого случая вывода.
Чтобы на вход в каждый метод приходило количество времени в секундах, а строка с выводом была одна на каждый вариант.
Например, метод printHoursMinsSecs(int s).

**Comment by javamasterpeople** [comment]
Исправлено в соответствиями с рекомендациями

**Comment by alka1ra** [comment]
+
отлично
