### ISSUE TITLE
NumberMultiplication, task 9

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#10]
[NumberMultiplication, task 9](https://github.com/javamasterpeople/javacorestart/blob/master/src/NumberMultiplication.java) 

Выполнено верно. 

_Незначительные улучшения_
1. Сделать более читабельный вывод чисел (например, вместо 3628800 -> 3 628 800 или 3,628,800 или ещё как-то так).

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
принято!
