### ISSUE TITLE
SimpleNumber, task 11

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#11]
[SimpleNumber, task 11](https://github.com/javamasterpeople/javacorestart/blob/master/src/SimpleNumber.java) 

Решено верно.

**Предложение по улучшению**
1. Вынести проверку, простое ли число, в отдельный метод.
2. Сейчас в коде обход чисел в цикле исполняется столько n раз, если число для проверки n. Т.е. если ввести число 8, то в цикле будет происходить вычисление остатка от деления первоначального числа на i ровно 8 раз. Можно подумать,как этого избежать - например, при нахождении следующего делителя, который больше единицы, сразу выходить из цикла.

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
+
