### ISSUE TITLE
CircleRectangle, task 7

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#12]
[CircleRectangle, task 7](https://github.com/javamasterpeople/javacorestart/blob/master/src/CircleRectangle.java) 

Решено верно.

_Предложения по доработке_
Опять же,можно всё по методам распределить - отдельно расчёт площади каждой фигуры, отдельно проверка, можно ли закрыть отверстие, отдельно - вывод

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
+ принято
один момент:
![image](https://user-images.githubusercontent.com/24397904/88227042-ac2b9a00-cc75-11ea-865e-4764158e0c2f.png)
это то же самое, что и:
![image](https://user-images.githubusercontent.com/24397904/88227082-bb124c80-cc75-11ea-894b-e917acc45f74.png)

первое проверки if (check) остаточно ;)
