### ISSUE TITLE
SumFirst3, task 12

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#13]
[SumFirst3, task 12](https://github.com/javamasterpeople/javacorestart/blob/master/src/SumFirst3.java) 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Решено не верно, к сожалению. Попробуй заменить с суммы первых 100 чисел на сумму первых 2. Результат - 0. А это неверно, ведь 3 + 6 = 9.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by javamasterpeople** [comment]
Исправлено

**Comment by alka1ra** [comment]
отлично! всё работает, закрываю issue.
