### ISSUE TITLE
ArrayCoup, task 15

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#16]
[ArrayCoup, task 15](https://github.com/javamasterpeople/javacorestart/blob/master/src/ArrayCoup.java) 

Решено верно.

_Доработка_
1. Сделать вывод массива отдельным методом, который и использовать каждый раз.

**Comment by javamasterpeople** [comment]
Доработка произведена

**Comment by alka1ra** [comment]
+ закрываю issue
