### ISSUE TITLE
SumMinToMax, task 16

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#17]
[SumMinToMax, task 16](https://github.com/javamasterpeople/javacorestart/blob/master/src/SumMinToMax.java)

Решено верно! 

_Доработка:_
разбить на методы :)

**Comment by javamasterpeople** [comment]
Доработано наверное =)

**Comment by alka1ra** [comment]
доработано :) 

ставлю плюсик за глобальные переменные, в данных условиях это отличное решение. позже узнаешь о них и о языке побольше - можно будет и без них ;)

но на сегодня issue закрываю
