### ISSUE TITLE
ArrayButterfly, task 17

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#18]
[ArrayButterfly, task 17](https://github.com/javamasterpeople/javacorestart/blob/master/src/ArrayButterfly.java)

Решено верно!

_Предложение_ - разбить на методы.
_Если будет время_ - подумать, как в одном методе объединить создание верхней и нижней части бабочки.

_Один момент еще_: переменные i, j используются только в циклах, каждый раз в каждом начале цикла им присваиваются новые значения. В целом, их видимость важна только в циклах. Поэтому объявлять их предпочтительнее только в цикле. 
Вместо:
![image](https://user-images.githubusercontent.com/24397904/87641667-19f53480-c751-11ea-8bda-e5280186891a.png)

Сделать:
![image](https://user-images.githubusercontent.com/24397904/87641624-0944be80-c751-11ea-88b2-5c15fce4b1f1.png)

**Comment by javamasterpeople** [comment]
исправлено

**Comment by alka1ra** [comment]
Вложенные массивы - отличное решение! 
принимаю, всё красиво.
