### ISSUE TITLE
ReturnNumber (task 4)

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#2]
[ReturnNumber, task 4](https://github.com/javamasterpeople/javacorestart/blob/master/src/ReturnNumber.java) 

Задача решена верно.

**Рекомендации по улучшению**
1. Сделать возможность ввода числа с любым количеством цифр (одно-,двух-, трёх-, пяти-,..., n-значное).
2. Получать не строку, состоящую из цифр конечного числа, а само число. Вместо String str = 4 + "" + 3 + "" + 2 получить int result = 432, который и вывести в методе печати.

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
принято
