### ISSUE TITLE
CompareNumbers (task 5)

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#3]
[CompareNumbers, task 5](https://github.com/javamasterpeople/javacorestart/blob/master/src/CompareNumbers.java) 

Задание решено верно.

**Рекомендации по улучшению:**
1. Следить за лишними знаками точка с запятой (";").
2. Сделать возможным ввод числа с любым количеством цифр (одно-, двух-, трёх-,... n-значное число).

**Comment by javamasterpeople** [comment]
Рекомендации выполнены

**Comment by alka1ra** [comment]
Задание засчитываю!

Один момент - если в числе одна цифра, то это же значит, что цифры не повторяются, т.е. они различны.

**Comment by javamasterpeople** [comment]
Эмм.. я сам не знал как в этом случае правильней, в любом случае там true на false поменять и все )

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
+
