### ISSUE TITLE
NumberCheck1 (task 6)

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#4]
[NumberCheck1, task 6](https://github.com/javamasterpeople/javacorestart/blob/master/src/NumberCheck1.java) 
Задание решено верно!

**Предложения по улучшению**
1. Создать отдельные методы на каждую проверку (в идеале - чтобы методы возвращали boolean значение).
2. Сделать проверку на количество цифр возможной для любого числа цифр (число цифр для проверки может передаваться в качестве параметра в метод, например boolean checkNumberSize(int number, int size), где number - исходное число, а size- количество цифр для проверки). В целом этот момент почти осуществлён, нужно только вместо counter  == 3 использовать counter == size.

_Незначительные возможные улучшения_
0. Не создавать не используемые переменные (см. переменная int size = 3) - или же использовать их.
1. Вместо if(условие) {переменная = true} else { переменная = false } можно использовать конструкцию переменная = условие.
Пример:
ДО: 
![image](https://user-images.githubusercontent.com/24397904/87600926-cc4edc80-c6fc-11ea-9be8-f1451f90486b.png)
После:
![image](https://user-images.githubusercontent.com/24397904/87600967-dbce2580-c6fc-11ea-9d60-cfc6deb594dc.png)

2. Хороший тон - использовать фигурные скобочки в IF-ELSE конструкциях, даже если внутри одна строчка. Так обычно более читабельно. 
3. Следить за сообщениями от Intellij IDEA, она обычно дельные вещи подсказывает,например:
![image](https://user-images.githubusercontent.com/24397904/87599523-416de200-c6fc-11ea-92c3-9a4c300d2162.png)

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
принято
