### ISSUE TITLE
MoneyMessage, task 8

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#6]
[MoneyMessage, task 8](https://github.com/javamasterpeople/javacorestart/blob/master/src/MoneyMessage.java)

Задание выполнено отлично! 

_Незначительные улучшения_
1. Хороший тон - использовать фигурные скобочки в IF-ELSE конструкциях, даже если внутри одна строчка. Так обычно более читабельно.

**Comment by javamasterpeople** [comment]
исполнено

**Comment by alka1ra** [comment]
принято
