### ISSUE TITLE
Fac, task 10

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#8]
[Fac, task 10](https://github.com/javamasterpeople/javacorestart/blob/master/src/Fac.java)

Задание решено верно!

**Рекомендованные улучшения**
1. Не считать факториал от 1 до числа (n) каждый раз, а использовать уже посчитанное значение. Т.е. вынести расчёт факториала от 1 до indexStart из цикла. И дальше использовать его и каждый последующий высчитанный факториал.

_Незначительные улучшения_
1. Сделать более читабельный вывод чисел (например, вместо 3628800 -> 3 628 800 или 3,628,800 или ещё как-то так).
2. Фигурный скобочки в цикле FOR - и вообще в циклах, даже если само тело цикла состоит из одной строки. Так обычно более читабельно тоже.

**Comment by javamasterpeople** [comment]
исправлено

**Comment by alka1ra** [comment]
принято
