### ISSUE TITLE
Hello world и HelloName

### ISSUE THREAD

**Issue by alka1ra** [javamasterpeople/javacorestart#9]
Задания [Hello world, таск 1](https://github.com/javamasterpeople/javacorestart/blob/master/src/Hello.java)
[Hello name, таск 2](https://github.com/javamasterpeople/javacorestart/blob/master/src/HelloName.java) 
Оба выполнены верно.

_Незначительные улучшения в Таск 2_
1. Можно имя вынести в отдельную переменную.

**Comment by javamasterpeople** [comment]
исправлено
